### ISSUE TITLE
Card for どれ has mismatching sentence and sentence audio.

### ISSUE THREAD

**Issue by ArctynFox** [donkuri/Kaishi#1]
As the issue title states, the card for the word どれ has a mismatching example sentence and sentence audio. While the sentence and sentence audio are both examples for the word, the sentence audio says "この中で、どれが好きですか。" while the text says "どれがいいですか。" Not a massive issue, but could be confusing.

**Comment by donkuri** [comment]
Seems we had the wrong file, thank you! Fixed in the latest version of the deck.
