### ISSUE TITLE
some word note suggestions

### ISSUE THREAD

**Issue by hudsonm62** [donkuri/Kaishi#14]
Just some suggestions to add to the card notes, word it however you like but I think it's vital the information is at least there:

- あまり - Mostly used with negatives to indicate "not much" or "not very"
- どれ - "which" among three or more options
- どちら - "which" among 2 options only. どっち is more commonly used in casual speech.
- 無い - The exact same usage as ない but used in formal/polite text (usually seen with です)

been using this deck for a few days now in prep for N5 coming up in a few months, thanks! will continue to make more suggestions/improvement notes as i find them

edit- keep in mind im still only around n5 level, im pretty sure im mostly correct though

**Comment by donkuri** [comment]
Hi, thanks for your comment! I will add the point for どれ and どちら (good point!), but あまり is used in both negative and positive sentences. In fact, it is a N2 grammar point in many popular grammar books. For instance, 「時間のあまりで」blablabla. As for 無い it isn't particularly more polite than ない, it's the same word just with 漢字. For instance, 沢山 can also be written たくさん.
