### ISSUE TITLE
動く word audio

### ISSUE THREAD

**Issue by FoxFireX** [donkuri/Kaishi#16]
This one I'm not sure about, but I think the word audio here is saying "うもく" instead of "うごく". If I'm hearing it wrong, sorry for the issue.

**Comment by JunkMeal** [comment]
I think you are hearing it wrong. The ご in there sounds nasalized so it might seem like も.

**Comment by donkuri** [comment]
I agree, I am pretty sure this one is correct but I will double-check it with a few people just to make sure.

**Comment by donkuri** [comment]
Yep, this is a typical case of nasalization. The こ is nasalized and thus sounds like うんごく or うもく. The same happens with すごい that is sometimes heard as すんごい. Either way, this is correct.
