### ISSUE TITLE
Cards that likely have mismatched highlighting between furigana and non-furigana sentence views

### ISSUE THREAD

**Issue by FoxFireX** [donkuri/Kaishi#17]
After seeing a few different cards where the highlighting didn't match between the furigana and non-furigana sentences, I decided to try to capture as many of those as I could for review at once. Here's what I did in case you want to repeat the process:
1. Export cards to text
2. Import into Google Sheets
3. Remove unnecessary columns
4. Search and replace regex "\[[^\[]*\]" with "" to remove all furigana characters and their delimiters.
5. Search and replace " " with "" to remove spaces.
6. Add a column with the equation "=IF(EQ(D1,E1),"OK","Differ")" so I can identify rows where the resulting text differs
7. Sort rows by this new column

At this point I manually reviewed the 17 rows I found in 1.1.5. Some of them are still okay and are just being tripped by other formatting stuff, but the following cards may need to be reviewed for highlighting discrepancies:

どんな
八
すぐ (This one seems to introduce the kanji only on the furigana version of the sentence.)
怒り
素晴らしい (Bold tag appears broken in the non-furigana sentence.)
買い物 (Furigana sentence possibly missing an い.)

**Comment by donkuri** [comment]
This is smart and I will run this on the latest version of the deck. Thank you very much!

**Comment by donkuri** [comment]
Done, thank you very much!
