### ISSUE TITLE
Set text language to Japanese in card template

### ISSUE THREAD

**Issue by Bobo1239** [donkuri/Kaishi#20]
I've noticed that on my phone AnkiDroid uses the wrong font variant for rendering the cards. (due to [Han unification](https://en.wikipedia.org/wiki/Han_unification))
This can be fixed by wrapping the front and back templates in a `div` which sets the language:
```html
<div lang="ja">
...
</div>
```
Not sure if there are other/easier methods to fix this.
Before/After:

<img src="https://github.com/donkuri/Kaishi/assets/2302947/cbc7556d-69a5-4988-a920-c3fb8c81bf15" width="300" />
<img src="https://github.com/donkuri/Kaishi/assets/2302947/b63d66c4-da20-4466-8fd9-1b114b6556f2" width="300" />

**Comment by donkuri** [comment]
Interesting, I didn't know that. Will fix this in the next release. Thank you!

**Comment by christopherball** [comment]
@donkuri Side question - when issues like this are fixed and a new release is created, what's the recommended approach to cleanly "upgrade" our existing deck without losing review progress?  The readme's "How to import Kaishi 1.5k on top of another deck" section seems tangentially related.

**Comment by donkuri** [comment]
@christopherball If you imported the `.apkg` file normal (i.e. not by modifying a Core deck or something) then you can simply reimport it, making sure that the option to update the cards are ticked (should be default). Worst case scenario, you can start by backing up everything and even if it doesn't work, you can just undo the import (literally `Ctrl+Z`).
