### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by mauriciolq** [donkuri/Kaishi#23]
Does this deck require a specific Anki version? My Windows desktop gets an error importing:

Import failed. Debugging info:
'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte

I'm using:
Version ⁨2.1.48 (fb07bad3)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Comment by donkuri** [comment]
This is written on the main page:

> You can either get the deck on the [releases](https://github.com/donkuri/Kaishi/releases/) page of this GitHub or on [AnkiWeb](https://ankiweb.net/shared/info/1196762551), provided the deck is not undergoing review. The deck is supported on Anki 2.1.50+.

If you want to use it, you'll have to update at least to 2.1.50.
