### ISSUE TITLE
Translation for Brazilian Portuguese

### ISSUE THREAD

**Issue by Yagxter** [donkuri/Kaishi#24]
I'm interested in translating this deck to share with my Japanese learning community and anyone who wants to benefit from this content and don't have a good English.

**Comment by donkuri** [comment]
No worries, please fork the project and upload the translation there, I will then link it back from there.

**Comment by FragozoLeonardo** [comment]
If you ever want a native Portuguese speaker with a decent level of English and so-so of Japanese, I'm here.

**Comment by Yagxter** [comment]
Thank you, I'm working on the translation

**Comment by donkuri** [comment]
Is this still being worked on?

**Comment by Yagxter** [comment]
Yeah, translation still in progress. It's just taking me a while because I translate the deck after work

**Comment by donkuri** [comment]
No worries, I'm just checking up on progress. Thanks for your work!
