### ISSUE TITLE
Sound cutoff

### ISSUE THREAD

**Issue by Chicadee987** [donkuri/Kaishi#25]
When using bluetooth headphones (sony wh-1000xm5) and AnkiDroid, some part or even all of Word Audio is cut off. 

I've noticed the issue before in other decks also and for this identified to at least the following:
- 手
- 目
- [声 (partially cut)

Steps to reproduce:
- Specific setup. No issues when using Anki on PC.
- Flip the card during study.
  - Word Audio is supposed to be played, followed by Sentence Audio. 

Let me know if you want me to test some fix candidates.

ps. ください has really background loud noise, but you prob already knew that..

BR

**Comment by donkuri** [comment]
This isn't an issue with Kaishi (you mentioned so yourself, it happens with other decks). This means it's an issue with Ankidroid itself, and this isn't where you should report it. Instead, please post directly on Ankidroid's issue tracker.

Regarding ください, yeah unfortunately it's the only one we had... Regardless, thanks for posting and good luck with your audio issue.

**Comment by abaga129** [comment]
Just thought I would chime in that this is an issue with how bluetooth earbuds work in general.  They have a fade in/out to prevent an assult on your eardrums. It happens on PC too.  On PC the work around is to have something else playing in the background at an inaudible volume like music or whitenoise.  On Android I'm not sure if you could do the same.
