### ISSUE TITLE
the card 子 is missing the pitch accents

### ISSUE THREAD

**Issue by HoaryBoulder** [donkuri/Kaishi#26]
As can be seen in the picture attached. I am fairly certain that I have the newest version of the deck

![Kaishiko](https://github.com/donkuri/Kaishi/assets/129270886/44609774-3856-4fde-a103-e2fdb3e1709f)

**Comment by donkuri** [comment]
That is normal because it's a one-mora word, this is how these are notated in general in this system of pitch notation. You cannot show a drop because this assumes there is more than one mora.
