### ISSUE TITLE
沢山 card shows hiragana reading on the front instead of kanji

### ISSUE THREAD

**Issue by abaga129** [donkuri/Kaishi#27]
The example sentence on the front shows as
`私には友達がたくさんいます。`

**Comment by donkuri** [comment]
Mmmh, I'm not sure whether to keep it like this or not. Technically, 沢山 is seen more often in full kana. I will think about it.

**Comment by abaga129** [comment]
Oh interesting. I wasn't aware of that.
My thoughts on that is having the kana reading on the front makes the card easier and less likely to memorize the reading of the kanji.  I would think that by learning this card, if one encountered the kana reading elsewhere, it would still be obvious that it's the same word, but I'm also just a learner so I'm speculating.

**Comment by donkuri** [comment]
Yes you are absolutely right, and it's also kind of inconsistent, but at the same time I like the fact learners at least see it once.

**Comment by donkuri** [comment]
Okay, I will keep it as it, I think it's fine the way it is.
