### ISSUE TITLE
Both of the 描く cards have the same furigana reading.

### ISSUE THREAD

**Issue by monadoenchant** [donkuri/Kaishi#32]
One should have the 描く[かく] reading, and the other should have the 描く[えがく] reading, but currently the furigana shows えがく for both of them.

**Comment by monadoenchant** [comment]
oops, wrong kanjis. edited that out

**Comment by donkuri** [comment]
This was fixed in a previous release, did you update the deck? If so, did it happen after updating?

**Comment by donkuri** [comment]
Okay, this is fixed in the latest version, please update.
