### ISSUE TITLE
違う using 答え

### ISSUE THREAD

**Issue by autoditactics** [donkuri/Kaishi#34]
I'm not sure if this was intentional or if something is weird on my end, but 違う uses 答え in the example sentence, which appears later in the deck. Same with 上 using 向く. Since the sentences that come with 答え and 向く use more basic vocabulary, they should appear first.

**Comment by donkuri** [comment]
Basically, not the entirety of the deck is i+1. We tried to strike a balance between frequency (which word is most common) and "i+1-ness" (how many new words are in a sentence). For the first 200 or so words, we tried sticking to i+1 principles, but after this we considered it less important than keeping with frequency information. Regardless, you are free to switch them around.
