### ISSUE TITLE
ようい preparation card

### ISSUE THREAD

**Issue by Kaizen5000** [donkuri/Kaishi#36]
The ようい card says that the word means "prepare, ready oneself" but doesn't that imply a verb whereas the dictionary definitions says "preparation, arrangements"

**Comment by donkuri** [comment]
用意 is both a noun and a する-verb, so 用意する means "to prepare, to ready oneself" but also as a noun "preparation, arrangements". If you take a look at the jmdict/jisho definition, you can see it says Noun, Suru verb, Transitive verb.
