### ISSUE TITLE
珍しい Audio and Text are Different

### ISSUE THREAD

**Issue by Ryu945** [donkuri/Kaishi#37]
The text says:

>こんなに大きなダイヤは珍しいです

The audio says:

> こんな大きなダイヤは珍しいです

From how I had it explained to me, they do not mean the same thing.  The first one means:

>A diamond this big is rare.

This emphasizes the size of the diamond.  The second means:

>This kind of big diamond is rare.

This can be talking about a quality other then size when it mentions. 

>This kind of

**Comment by donkuri** [comment]
Oh this is a really good catch thank you, will update this now!
