### ISSUE TITLE
何だか Possibly fix the English grammar

### ISSUE THREAD

**Issue by Ryu945** [donkuri/Kaishi#38]
The 何だか card has the sentence.

>Seeing the tea leaves floating upright, somehow I feel happy.

I think this is technically correct but it is rather strange sounding in English.  I noticed the original English sentence follows Japanese grammar structure.  I believe this would be a better sentence.

>Somehow I feel happy when I see the tea leaves floating upright.

Another possibility

>Somehow I feel happy seeing the tea leaves floating upright.

**Comment by donkuri** [comment]
I think this is minor personally, and the structure of the English sentence reflects that of the Japanese sentence, which in this case makes it easier to understand in my opinion. I'll ask Tyogin what he thinks and if he agrees I'll change it, thank you!

**Comment by donkuri** [comment]
Yeah he agrees that the translation being closer to the Japanese sentence is a good thing here so I'll close it, feel free to change it on your own version of the deck though.

**Comment by Ryu945** [comment]
That is probably for the best.  I thought I should mention it though.
