### ISSUE TITLE
次 - bad audio

### ISSUE THREAD

**Issue by cakiya** [donkuri/Kaishi#40]
次（つぎ） is pronounced as つに for some reason
https://github.com/user-attachments/assets/be010147-e5b8-4cd1-87bc-baa4ae147144

**Comment by Foyerr** [comment]
つに pronunciation is on [Jisho](https://jisho.org/word/%E6%AC%A1) as well, but I have another audio clip from my dictionary with the [つぎ ](https://github.com/user-attachments/assets/9f631a9c-9af0-4830-9646-efa88c538647) pronunciation

**Comment by donkuri** [comment]
This is not つに, it is pronounced つぎ with a nasalized ぎ, you can read about it [here](https://www.youtube.com/watch?v=xpzpbuFHVVU).
