### ISSUE TITLE
Adding new cards with the Kaishi format

### ISSUE THREAD

**Issue by ajbjc** [donkuri/Kaishi#41]
There isn't a discussion page so I'm doing it as an issue. I have yomitan connected to anki, and I can choose to send new words to the kaishi deck and kaishi model (the fields). However, I don't know how to get it so that, when exported to anki, sentences appear formatted correctly. As for pitch accents, which style is used, Javdejong or Kanjium?

**Comment by donkuri** [comment]
I personally would not modify the deck directly, instead configure a mining deck directly ([I have a guide on my website](https://donkuri.github.io/learn-japanese/mining/)) and choose Kaishi as a model. To get the sentences to be formatted correctly, you will have to copy-paste the Front, Back and Styling options detailed on this GitHub page (but also on your deck) into the new mining deck. As for pitch accent, I must admit I don't remember what we used, simply try out the various options and see which one corresponds, or which one you like best.

**Comment by ajbjc** [comment]
Hope you don't me asking, but why is it better to put new cards in a separate deck deck despite having the same format? I've only been using it for just over 2 weeks and have only mined 1 word.

**Comment by donkuri** [comment]
You don't need to do it if you properly tag your cards I guess, but I've always been a big proponent of separating things. That allows for cleaner decks. You can put both your mining deck and kaishi into a bigger "Japanese" deck if you want.
