### ISSUE TITLE
Issues with some cards

### ISSUE THREAD

**Issue by ajbjc** [donkuri/Kaishi#42]
The card for について has very quiet word audio compared to the sentence audio, or any of the other audio clips I've heard so far.

Also, I feel like some meanings could be improved when it comes to multiple Japanese words with the same given meaning in the deck. What I mean is that when it comes to different ways of saying "I" or "you" it says when they're used, i.e. formal, male, etc; but then there's two words to "return, to back" for example, and doesn't give an indication as to the exact difference in meaning. Or how there's two words for big/large: 大きい and 大きな.

**Comment by donkuri** [comment]
Regarding the について issue, I will look into it. As for the specific nuances behind these words, we do not provide very detailed nuance breakdowns because we believe those are best learned through immersion instead. If you have something very specific in mind, feel free to mention it on this issue.

**Comment by ajbjc** [comment]
I also noticed something with the card そもそも, sentence audio is fine but the word audio sounds like she's saying ふもふも instead.

**Comment by donkuri** [comment]
Thank you, I fixed the issue with について. As for そもそも, I hear it correctly and so do others, I think it's just a bit poorly articulated.
