### ISSUE TITLE
Mistake report

### ISSUE THREAD

**Issue by dubai03nsr** [donkuri/Kaishi#45]
どれ (18): "(lit., Which one is good?)" in the translation is incorrect.
一 (205): The pitch accent should be odaka.
八 (212): The pitch line extends over the first mora too.
日 (306): 匕→ヒ in the pitch accent.
幸せ (415): 良 furigana よ→い
地面 (648): 描 furigana えが→か
見守る (1159): 皆 furigana みな→みんな
雪 (1273): 降 furigana お→ふ
全体 (1357): "80" should have furigana はちじゅっ.
永遠 (1423): 手間→テーマ
金曜日 (1492): The sentence (without furigana) has an extra "]".

**Comment by donkuri** [comment]
Thanks, I will mention this to the people taking care of pitch accent and fix the rest as soon as I have time.

**Comment by donkuri** [comment]
Hello, thanks again! This should be fixed in the latest version I am releasing soon.
