### ISSUE TITLE
add padding to word and sentence furigana

### ISSUE THREAD

**Issue by icebarf** [donkuri/Kaishi#47]
When looking at furigana for kanji in the deck, the characters are super close to each other making it hard to focus on the individual kanji itself. Is there a way to add padding to it? I tried to change a few things in the back template of cards using CSS but couldn't exactly figure out how to do it. I have attached a couple screenshots so that you know what I am talking about. Any help would be appreciated.

![image](https://github.com/user-attachments/assets/20dbe259-6414-400d-ae7a-a36f96f75415)
![image](https://github.com/user-attachments/assets/90afbe89-3b6e-49d5-b8a0-1e91bacddeb2)

**Comment by icebarf** [comment]
Adding "Noto Sans CJK JP" to the Styling fixed it. Thank you. Perhaps could include it by default in the deck?

Leaving this open for now.

**Comment by icebarf** [comment]
![image](https://github.com/user-attachments/assets/592f64f1-7d4f-45a7-9e31-50741636b208)

**Comment by donkuri** [comment]
I'd rather not bundle fonts with the deck, but this is also pretty surprising as I had tested the deck with other fonts too. What font were you using, out of curiosity?

**Comment by icebarf** [comment]
I had installed `noto-fonts-cjk` on my computer.

> I'd rather not bundle fonts with the deck
Sorry, I didn't imply this. I mean including "Noto Sans CJK JP" in the Style template of the deck (as shown in my latest screenshot)

**Comment by donkuri** [comment]
@icebarf I added "Noto Sans CJK JP" in the style just in case, thank you!
