### ISSUE TITLE
Translation to Indonesian

### ISSUE THREAD

**Issue by penganggur** [donkuri/Kaishi#50]
Hi mate, sorry for late contact. I want to inform that I have been translating kaishi to Indonesian. I also adding some note for the first card and also add a little footer (but not remove the original caption).
Is it okay or I need to edit something?

This is my all anki work. Please let me know your though.
https://ankiweb.net/shared/by-author/1371410913

Thank you.

**Comment by donkuri** [comment]
Looks great, thanks for notifying me! I will add you to the list of translations.
