### ISSUE TITLE
Furigana and base fields can be merged

### ISSUE THREAD

**Issue by Logabe** [donkuri/Kaishi#52]
Anki supports using `kanji:` and `furigana:` show either just the Kanji, or the Kanji with Furigana.
I think merging the Base and Furigana fields for words and sentences would make adding new cards easier for people who are using the deck template.
I've modified my card and note types to remove the redundant fields and can provide the formatting if you wish. I've just started using your wonderful deck, and wanted to make it a little bit easier for myself to move my existing notes over to this format.
If there's a reason that you've decided to not implement this, please let me know - I'd be genuinely interested to know :D

**Comment by Logabe** [comment]
One thing I've noticed about this is that it means that you can't search for a note using only the kanji, you have to type the hiragana in as well. I don't know if there's a setting to fix this, but I think it's probably not worth changing it unless there is since it makes searching for cards a lot harder.

**Comment by donkuri** [comment]
Good to know, I'll keep that in mind if I do use it, thank you.
