### ISSUE TITLE
くん card lacking furigana

### ISSUE THREAD

**Issue by dede6giu** [donkuri/Kaishi#56]
"1" lacking furigana, wouldn't 健[けん]<b>くん</b>は １[いっ] 歳[さい]です be correct?

![Screenshot_20241222-105500_AnkiDroid.png](https://github.com/user-attachments/assets/16fc92a1-bcc7-45e6-8f5c-cc2161a78ee0)

**Comment by donkuri** [comment]
To avoid really long furigana on long numbers (such as date), we decided to not add furigana for numbers, this is why this one doesn't have it. Feel free to add it yourself by modifying the `[さい]` into `[いっさい]` and adding a space between は and 1.
