### ISSUE TITLE
Dialogue markings in ありがとうございます 

### ISSUE THREAD

**Issue by dede6giu** [donkuri/Kaishi#57]
![Screenshot_20241225-123622_AnkiDroid.png](https://github.com/user-attachments/assets/d22d5841-8595-4c24-b637-e04d1056e38a)

There is a dialogue marking subject "A" and their speech 「」 without actual dialogue

**Comment by donkuri** [comment]
Thanks, will take this one out as well. I'll wait for a while to see if a few more pop up.
