### ISSUE TITLE
Audio for some words doesn't play on iPhone Anki app

### ISSUE THREAD

**Issue by Pasqetti** [donkuri/Kaishi#6]
This is probably because the audio is an .ogg file which the iPhone says is not supported.

I don't know what proportion of the cards use .ogg files, but for the ones that do, the audio for the word is unable to be played using the Anki app on an iPhone. 

If it's only a small number of basic vocab or if there's alternative audio that'd be helpful. Its looking like a great deck so far.

**Comment by donkuri** [comment]
Okay, this is a pretty big problem and one I did not anticipate. I will try to convert all the files to .mp3.

**Comment by donkuri** [comment]
I converted the .ogg files into .mp3, this should fix the issue. Thank you for reporting it, this was pretty big! Fixed in the latest version of the deck.
