### ISSUE TITLE
Add images according to the word

### ISSUE THREAD

**Issue by Soymilkrice** [donkuri/Kaishi#8]
Yes,
Just like Core 2k/6k deck, it would be a much nicer environment for the beginners, do not get lost.

**Comment by donkuri** [comment]
Hi, I agree pictures would be nice but core only had partial pictures for less than half of the deck, and since Kaishi has even less of these, we decided to not include any pictures. I toyed with the idea of using AI to generate pictures but I found it unsatisfactory. If you would like to compile pictures, then you're very welcome to do so. If the pack is good enough, I'll consider merging them in the decks and letting people choose to enable them or not.

**Comment by ChrolloRifat** [comment]
> Hi, I agree pictures would be nice but core only had partial pictures for less than half of the deck, and since Kaishi has even less of these, we decided to not include any pictures. I toyed with the idea of using AI to generate pictures but I found it unsatisfactory. If you would like to compile pictures, then you're very welcome to do so. If the pack is good enough, I'll consider merging them in the decks and letting people choose to enable them or not.

I think that would be awesome.

**Comment by FragozoLeonardo** [comment]
I think that Irastoya pictures can be great, they are simple and use-free.

**Comment by woofingcough** [comment]
It would be great if the deck at least had an image field so that I could add pictures as I review them.

**Comment by donkuri** [comment]
> It would be great if the deck at least had an image field so that I could add pictures as I review them.

You can simply add one yourself. Go to `Tools > Manage Note Types` (or click Ctrl+Shift+N) and then choose `Kaishi 1.5k` and click on `Fields` in the right then finally `Add`. You can simply call the new field whatever you want.

Until we have a full set of images, I won't be modifying the note myself.

**Comment by Soymilkrice** [comment]
> I think that Irastoya pictures can be great, they are simple and use-free.

Irastoya pictures ? Looks interesting, maybe I could do this for every card and pull them to the project?

**Comment by donkuri** [comment]
If you do so, don't hesitate to send me the .apkg and I will review it. If it turns out to be good, I will update kaishi directly. If you do go through with this, send me:

1. The deck's APKG
2. A folder with all the pictures

Good luck and thank you!

**Comment by liarbeast** [comment]
Hello everyone! I believe one of the main challenges with adding illustrations is the significant effort required to gather 1,500 pictures. Working together would help speed up the process considerably. I've created a publicly editable spreadsheet [here](https://docs.google.com/spreadsheets/d/1XrumAlaWRkhw_OafqQZwhr7qiyLUTIhAsNyz9AJk_7s/) containing all Kaishi notes and a new column for images.

Now, I'm curious if anyone has suggestions on how to display images from URLs in Anki. While direct linking is an option, it relies on internet connectivity and links can become broken. Maybe there's a way to convert/download them and attach them to the note? My knowledge of Anki is very limited, but I'm happy to take a crack at it if anyone has some pointers.

Other than a spreadsheet, we could also simply download all of them and put them in a folder but once again I don't know how to automate the linking of images to notes.

I've already added a few images using Irasutoya illustrations from [this search engine](https://cse.google.com/cse?q=&cof=FORID%3A0&cx=partner-pub-7640247339000071%3A0803135029). These illustrations are quite fitting for our purposes and cover a wide range of contexts. Additionally, they're transparent, making them suitable for Anki.

I'm eager to hear your thoughts and ideas. But these were my suggestions.

**Comment by liarbeast** [comment]
Hi all. I've been working on this and have made some great progress. I'm hoping to have a first version ready end of this week or the next.

**Comment by liarbeast** [comment]
Hey I've finished the deck. I'm pretty happy with it, I think it looks cool and it's more useful than I thought. What shall I do with it? Does someone want to check it?

**Comment by ChrolloRifat** [comment]
show us some samples, a video recording or screenshots maybe?

**Comment by liarbeast** [comment]
I made a fork of the deck here so you can try it out: https://github.com/liarbeast/Kaishi_pictures
Below are some screenshots.


<img width="400" alt="Screenshot 2024-04-20 at 10 23 33" src="https://github.com/donkuri/Kaishi/assets/17064080/ff5e5044-bff5-4511-ab35-31a88f29ebf8">
<img width="400" alt="Screenshot 2024-04-20 at 10 23 16" src="https://github.com/donkuri/Kaishi/assets/17064080/41f1208e-f681-48e3-97a8-dfcdfe47a3be">
<img width="400" alt="Screenshot 2024-04-20 at 10 22 29" src="https://github.com/donkuri/Kaishi/assets/17064080/9779c274-5f51-45be-a52f-da2fc5b772c8">
<img width="400" alt="Screenshot 2024-04-20 at 10 22 19" src="https://github.com/donkuri/Kaishi/assets/17064080/db0a82bb-9845-4193-baf9-dc5631c1d1dc">

**Comment by Soymilkrice** [comment]
THAT IS AMAZING.
I was also working on adding images into the deck, but you did it quite better than me. I'm really impressed.

Now you need to make a folder with all the images and send the modified apkg to donkuri.

**Comment by ChrolloRifat** [comment]
LGTM

**Comment by donkuri** [comment]
This looks fantastic! I will check the images and if they're all good, I'll merge it directly. If not, we can see if we can find better irasutoya images for a few specific ones.

**Comment by donkuri** [comment]
This is being worked on currently, it will be available in the next release cycle.

**Comment by ChrolloRifat** [comment]
SGTMM

**Comment by donkuri** [comment]
This is finally done, see the Kaishi 1.5k v2.0 release. Thank you everyone!

**Comment by Soymilkrice** [comment]
I'm so happy people did it, thank you all! Congratulations!
